### ISSUE TITLE
Audio issues

### ISSUE THREAD

**Issue by Cuzziwuzzi** [DeathWrench/BestestTVMod#4]
I have a large folder of heavily compressed videos and there's problems with loading some of them.
Occasionally the videos either end slightly sooner than they should, and other times the audio randomly skips forwards in time leading to popping artifacts and messed up rhythm

Its really bad with this video specifically

https://github.com/DeathWrench/BestestTVMod/assets/119263922/6f79d2f0-9402-4ad5-accb-75ca2f9d4ce0

https://github.com/DeathWrench/BestestTVMod/assets/119263922/b68c7309-b242-422a-be34-ec9dcda7d8ea

**Comment by DeathWrench** [comment]
Is it the same with TVLoader?

**Comment by Cuzziwuzzi** [comment]
> Is it the same with TVLoader?

It is

Rattenbonkers seems to not be active in modding anymore though

**Comment by Cuzziwuzzi** [comment]
Wrong button lol

**Comment by DeathWrench** [comment]
I think I fixed it, tell me if 1.1.0 resolves the issue.

**Comment by Cuzziwuzzi** [comment]
Nope :P

**Comment by DeathWrench** [comment]
It also happens with LethalTVManager?

**Comment by DeathWrench** [comment]
Re-open if the issue persists.

**Comment by Cuzziwuzzi** [comment]
Late response, sorry. LethalTVManager is also broken, and it still persists on newest version of this one

**Comment by FweeGamerHD** [comment]
Unfortunately it seems like this mod causes the tv to just go full silent for me.
Otherwise seems to work great.
